import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SESI_SENAI
 */
public class CassinoJorges extends javax.swing.JFrame {
    private String nome;
    private int valor_entrada = 0;
    private int fichas_compradas = 0;
    private int quantidade_fichas_10;
    private int quantidade_fichas_50;
    private int quantidade_fichas_100;
    private int quantidade_fichas_500;
    private int quantidade_fichas_1000;
    private int quantidade_fichas_5000;
    private int troco = 0;
    
    /**
     * Creates new form CassinoJorges
     */
    public CassinoJorges() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        campo_nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campo_valor_entrada = new javax.swing.JTextField();
        jorge_10_botao = new javax.swing.JButton();
        jorge_100_botao = new javax.swing.JButton();
        jorge_50_botao = new javax.swing.JButton();
        jorge_1000_botao = new javax.swing.JButton();
        jorge_500_botao = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jorge_5000_botao = new javax.swing.JButton();
        jorgesLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        trocoLabel = new javax.swing.JLabel();
        botaoJogar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jButton4.setText("jButton2");

        jButton6.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Jorge's Cassino");

        campo_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_nomeActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        jLabel3.setText("Valor de entrada:");

        campo_valor_entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_valor_entradaActionPerformed(evt);
            }
        });

        jorge_10_botao.setText("J$ 10");
        jorge_10_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jorge_10_botaoActionPerformed(evt);
            }
        });

        jorge_100_botao.setText("J$ 100");
        jorge_100_botao.setMaximumSize(new java.awt.Dimension(61, 32));
        jorge_100_botao.setMinimumSize(new java.awt.Dimension(61, 32));
        jorge_100_botao.setPreferredSize(new java.awt.Dimension(61, 32));
        jorge_100_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jorge_100_botaoActionPerformed(evt);
            }
        });

        jorge_50_botao.setText("J$ 50");
        jorge_50_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jorge_50_botaoActionPerformed(evt);
            }
        });

        jorge_1000_botao.setText("J$ 1.000");
        jorge_1000_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jorge_1000_botaoActionPerformed(evt);
            }
        });

        jorge_500_botao.setText("J$ 500");
        jorge_500_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jorge_500_botaoActionPerformed(evt);
            }
        });

        jLabel4.setText("Jorges:");

        jorge_5000_botao.setText("J$ 5.000");
        jorge_5000_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jorge_5000_botaoActionPerformed(evt);
            }
        });

        jLabel6.setText("Troco:");

        botaoJogar.setText("JOGAR");
        botaoJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoJogarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("* São necessários no mínimo J$10 para jogar *");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jorge_10_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jorge_50_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jorge_100_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jorge_500_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jorge_1000_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jorge_5000_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campo_nome)
                            .addComponent(campo_valor_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jorgesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trocoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(botaoJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campo_valor_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(trocoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jorgesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jorge_10_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jorge_100_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jorge_50_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jorge_500_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jorge_1000_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jorge_5000_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jorge_50_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jorge_50_botaoActionPerformed
        int valor_ficha = 50;
        if(troco >= valor_ficha) {
            quantidade_fichas_50 = quantidade_fichas_50 + 1;
        }
        compraFichas(valor_ficha);
    }//GEN-LAST:event_jorge_50_botaoActionPerformed

    private void campo_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_nomeActionPerformed
        nome = campo_nome.getText();
        JOptionPane.showMessageDialog(null, nome);
    }//GEN-LAST:event_campo_nomeActionPerformed

    private void campo_valor_entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_valor_entradaActionPerformed
        
    }//GEN-LAST:event_campo_valor_entradaActionPerformed

    private void jorge_10_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jorge_10_botaoActionPerformed
        int valor_ficha = 10;
        if(troco >= valor_ficha) {
            quantidade_fichas_10 = quantidade_fichas_10 + 1;
        }
        compraFichas(valor_ficha);
    }//GEN-LAST:event_jorge_10_botaoActionPerformed

    private void jorge_100_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jorge_100_botaoActionPerformed
        int valor_ficha = 100;
        if(troco >= valor_ficha) {
            quantidade_fichas_100 = quantidade_fichas_100 + 1;
        }
        compraFichas(valor_ficha);
    }//GEN-LAST:event_jorge_100_botaoActionPerformed

    private void jorge_500_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jorge_500_botaoActionPerformed
        int valor_ficha = 500;
        if(troco >= valor_ficha) {
            quantidade_fichas_500 = quantidade_fichas_500 + 1;
        }
        compraFichas(valor_ficha);
    }//GEN-LAST:event_jorge_500_botaoActionPerformed

    private void jorge_1000_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jorge_1000_botaoActionPerformed
        int valor_ficha = 1000;
        if(troco >= valor_ficha) {
            quantidade_fichas_1000 = quantidade_fichas_1000 + 1;
        }
        compraFichas(valor_ficha);
    }//GEN-LAST:event_jorge_1000_botaoActionPerformed

    private void jorge_5000_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jorge_5000_botaoActionPerformed
        int valor_ficha = 5000;
        if(troco >= valor_ficha) {
            quantidade_fichas_5000 = quantidade_fichas_5000 + 1;
        }
        compraFichas(valor_ficha);
    }//GEN-LAST:event_jorge_5000_botaoActionPerformed

    private void botaoJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoJogarActionPerformed
        if(fichas_compradas >= 10){
            if (troco > 0){
                JOptionPane.showMessageDialog(null, "Você recebeu R$" + troco + " de troco!");
            }
            JOptionPane.showMessageDialog(null, "Divirta-se!");
            MenuJogos frame = new MenuJogos();
            frame.iniciaFichas(fichas_compradas);
            frame.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Fichas insuficientes! (São necessários 10 jorges para jogar)");
        }
    }//GEN-LAST:event_botaoJogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CassinoJorges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CassinoJorges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CassinoJorges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CassinoJorges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CassinoJorges().setVisible(true);
            }
        });
    }
    
    public void compraFichas(int valor_ficha) {
        valor_entrada = Integer.parseInt(campo_valor_entrada.getText());
        troco = valor_entrada - fichas_compradas;
        
        if (troco >= valor_ficha){
            fichas_compradas = fichas_compradas + valor_ficha;
            troco = troco - valor_ficha;
            jorgesLabel.setText("J$ " + Integer.toString(fichas_compradas));
            trocoLabel.setText("R$ " + Integer.toString(troco));
        } 
        else {
            JOptionPane.showMessageDialog(null, "Valor de entrada insuficiente para comprar essa ficha.");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoJogar;
    private javax.swing.JTextField campo_nome;
    private javax.swing.JTextField campo_valor_entrada;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jorge_1000_botao;
    private javax.swing.JButton jorge_100_botao;
    private javax.swing.JButton jorge_10_botao;
    private javax.swing.JButton jorge_5000_botao;
    private javax.swing.JButton jorge_500_botao;
    private javax.swing.JButton jorge_50_botao;
    private javax.swing.JLabel jorgesLabel;
    private javax.swing.JLabel trocoLabel;
    // End of variables declaration//GEN-END:variables
}
